# Generated by Django 4.1.7 on 2023-06-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBookOasis', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Се процесира'), ('Deliver', 'Испратена на адреса')], default='Processing', max_length=100),
        ),
    ]
